version: '3'
services:
  bot:
    build: ./DaisukiSutoka
    volumes:
      - ./deploy/DaisukiSutoka:/DaisukiSuoka
    env_file:
      - ./DaisukiSutoka/.env
  mongo:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    volumes:
      - ./deploy/db:/data/db
    env_file:
      - ./.env
  api:
    build: ./api
    volumes:
      - ./deploy/api:/api
    ports:
      - "4433:4433"
    stdin_open: true
    tty: true
    env_file:
      - ./api/.env
      