version: '3'
services:
  bot:
    build: ./DaisukiSutoka
    volumes:
      - ./deploy/DaisukiSutoka:/DaisukiSuoka
    env_file:
      - ./DaisukiSutoka/.env
  mongo:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    volumes:
      - ./deploy/db:/data/db
    environment:
      - ./.env
      